name: CI
on:
  pull_request:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

jobs:

  test:
    name: Test ${{ matrix.rust-version }}
    strategy:
      matrix:
        rust-version:
          - stable
          - beta
          - nightly
          - msrv

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      # - name: Setup Cashix
      #   uses: cachix/cachix-action@v10
      #   with:
      #     name: mycache
      #     signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      #     authToken: ${{ secrets.CACHIS_AUTH_TOKEN }}

      - name: Build and Test
        run: nix build --log-format raw -L .#ci-${{ matrix.rust-version }}

      - name: Extra Checks
        if: matrix.rust-version == 'stable'
        run: nix flake check --log-format raw -L
